//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library3700.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemStatusLog
    {
        public int ItemStatusLogId { get; set; }
        public int ItemId { get; set; }
        public byte ItemStatusTypeId { get; set; }
        public System.DateTime LogDateTime { get; set; }
        public Nullable<int> AccountId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Item Item { get; set; }
        public virtual ItemStatusType ItemStatusType { get; set; }
    }
}
