
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Library3700.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ItemStatusType
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ItemStatusType()
    {

        this.ItemStatusLogs = new HashSet<ItemStatusLog>();

    }


    public byte ItemStatusTypeId { get; set; }

    public string ItemStatusName { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ItemStatusLog> ItemStatusLogs { get; set; }

}

}
