//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library3700.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int LoginId { get; set; }
        public string Username { get; set; }
        public string PasswordHash { get; set; }
        public bool IsPasswordTemporary { get; set; }
        public int AccountId { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
